### PR TITLE
Custom DB Connection 

### PR DESCRIPTION
**Pull request by victayo**
Enable users to set a DB connection for the model and migration. This is useful if a project has multiple DB connections and the DB for logging is not the default DB

### CODE REVIEW

**Comment by yoeriboven** [comment]
Thanks for the PR. I made some changes.

Haven't been able to test it on different connections so could you do that?

Please try with the default connection and then with the environment variable set.

**Comment by yoeriboven** [comment]
If anyone is looking for this functionality please test this branch if it works. If it does I will merge it and release it.

**Comment by PetrKaterinak** [comment]
Which branch? Tried composer require yoeriboven/laravel-log-db:dev-main and it is not present there

**Comment by yoeriboven** [comment]
This PR.

**Comment by inDeev** [comment]
I was not able to find how PR could be required by composer. So I decided to put files directly into my project and with custom db connections it works just fine. I'm using stancl/tenancy And I want to log anything in Central DB, without this PR it doesn't worked

**Comment by yoeriboven** [comment]
Merged and released. Please require `1.3` in your projects.

**Pull request merged**
