### PR TITLE
Laravel 10 Compatibility

### PR DESCRIPTION
**Pull request by padalton**

### CODE REVIEW

**Comment by yoeriboven** [comment]
Thanks for the PR. I'm looking into it right now so don't make any other changes ;)

**Comment by yoeriboven** [comment]
I pushed my changes directly to `main`. I'll tag a new version in a minute.

**Comment by padalton** [comment]
Didn't want to stress you.
I just thought i could help you with a pull request.
Btw this was my first pull request to a public repo ever 🎉

Yoeri Boven ***@***.***> schrieb am Di., 7. März 2023, 20:17:

**Comment by yoeriboven** [comment]
Yeah really appreciate it! Didn't stress me at all. :) 

Congrats on your first PR. Really helped me to know where to look :)

**Comment by yoeriboven** [comment]
@padalton I just created a new release that fixes a bug around exception reporting. You might want to upgrade to 1.1.1. :)

**Pull request closed without merging**
